version: "3.3"
services: 
  web: 
    build: .
    ports: 
      - 5000:5000
    volumes:
      - ./:/usr/src/app
    command: python run.py
    environment: 
      FLASK_ENV: ${FLASK_ENV:-development}
      PORT: ${PORT:-5000}
